[package]
name = "getlla-jni"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
android_logger = "0.15.1"
getlla = { path = "../../../" }
jni = "0.21.1"
log = "0.4.27"

[lib]
crate-type = ["cdylib"]
