[package]
name = "getlla"
version = "0.1.0"
edition = "2024"

[dependencies]

# [target.'cfg(target_os = "android")'.dependencies]
ndk = "0.9.0"
jni = "0.21"
log = "0.4.27"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.1"
objc2-core-location = "0.3.1"
objc2-foundation = "0.3.1"
